### ISSUE TITLE
1.10.2-0.1.3 - server-side issues?

### ISSUE THREAD

**Issue by silent-mobious** [halvors/Nuclear-Physics#1]
Hi there, awesome to see that you're remaking a classic!  Looks like I'm having some issues on the server-side, tho, related to block rendering?

Thanks!

**Mod Versions tested**: nuclearphysics-1.10.2-0.1.3
**Forge version used**: forge-1.10.2-12.18.3.2281-universal
**Log**: 
[19:18:47] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@66908303:
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/statemap/IStateMapper
        at org.halvors.nuclearphysics.common.init.ModBlocks.<clinit>(ModBlocks.java:48) ~[ModBlocks.class:?]
        at org.halvors.nuclearphysics.common.init.ModBlocks$RegistrationHandler.registerBlocks(ModBlocks.java:74) ~[ModBlocks$RegistrationHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_RegistrationHandler_registerBlocks_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:636) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588) [EventBus.class:?]
        at net.minecraftforge.fml.common.registry.PersistentRegistryManager.fireRegistryEvent(PersistentRegistryManager.java:98) [PersistentRegistryManager.class:?]
        at net.minecraftforge.fml.common.registry.PersistentRegistryManager.fireRegistryEvents(PersistentRegistryManager.java:85) [PersistentRegistryManager.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:622) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.statemap.IStateMapper
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        ... 15 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        ... 15 more

**Comment by halvors** [comment]
@silent-mobious Thanks for your bug report! The issue has been adressed in the latest alpha release.
